# Generated by Django 5.1.4 on 2025-01-09 23:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagem",
            name="criado_em",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 9, 23, 58, 29, 782780, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="postagem",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
    ]
